name: Run-Junit-Tests
on: [push]
jobs:
  junit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - run: java -cp java AWSTest
